---
version: 2
workflows:
  version: 2
  heroku_deploy:
    jobs:
      - deploy

jobs:
  deploy:
    docker:
      - image: circleci/node:10.14.1

    steps:
      - checkout

      - run:
          name: Deploy to Heroku
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master --force
